######################## default configuration ####################
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Organic Motherland Foods"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "About Us"
URL = "about-us"
weight = 4

[[menu.main]]
name = "Testimonials"
URL = "blog"
weight = 3

[[menu.main]]
name = "Products"
URL = "product"
weight = 2

[[menu.main]]
name = "Social Justice"
URL = "#"
weight = 5

[[menu.main]]
name = "Contact Us"
URL = "contact-us"
weight = 8

[[menu.main]]
name = "Recipes"
URL = "#"
weight = 6

[[menu.main]]
name = "Delivery Area"
URL = "subscribe"
weight = 7

#################### default parameters ################################
[params]
logo = "images/mlf-logo.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com) Reimagined by [Christina Design & Development](https://www.christinaharris.dev/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>VLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "016742 323313"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "Durham NC USA"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "rest@gmail.com - rest@mail.ru"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"